# This is a basic workflow to help you get started with Actions

name: CI Workshop App

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - price
    - update
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "laravel-tests"
  laravel-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Specifies the php version used in the Github Action
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Copy the right .env file to use a specific configuration
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      # Installs composer dependencies
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      # Installs wkhtmltopdf binary and dependencies
      - name: Install wkhtmltopdf binary
        run: |
          sudo apt-get install xfonts-75dpi
          sudo apt-get install xfonts-base
          sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt -f install

      # Setups Laravel key
      - name: Generate Key
        run: php artisan key:generate

      # Creates the sqlite database
      - name: Create DB and schemas
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate

      # Executes the tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
